name: Release to CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Check running containers
        run: docker-compose -f docker-compose.test.yml ps

      - name: Check logs
        run: docker-compose -f docker-compose.test.yml logs kafka-websocket-server

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: |
            geometrylabs/kafka-websocket-server:latest
            geometrylabs/kafka-websocket-server:${{ steps.source.outputs.TAG }}
